// Import AuthenticatedUser interface for type augmentation
import type { AuthenticatedUser } from '../auth/interfaces/authenticated-user';
// Import PermissionResolution interface for RBAC caching
import type { PermissionResolution } from '../iam/rbac/permission.types';

/**
 * TypeScript declaration file - Augments Express Request interface
 * Adds custom properties to Express Request type for better type safety
 * throughout the application
 */
declare global {
  namespace Express {
    interface Request {
      /**
       * Authenticated user object from JWT verification
       * Populated by JwtAuthGuard after successful authentication
       * undefined indicates an unauthenticated request
       */
      user?: AuthenticatedUser;

      /**
       * Unique correlation ID for distributed tracing
       * Generated by requestIdMiddleware for each request
       * Used in logs and error responses
       */
      requestId?: string;

      /**
       * Cached RBAC permission resolution for this request
       * Populated by RBAC guards to avoid redundant permission lookups
       * Phase B feature for fine-grained role-based access control
       */
      rbac?: PermissionResolution;
    }
  }
}

// Empty export to make this a module (required for declaration merging)
export {};
